### ISSUE TITLE
大佬，这个是模拟的请求吗

### ISSUE THREAD

**Issue by jiangdengke** [Changbaiqi/QuickBot#1]
Request request = new Request.Builder()
                .url("https://ai.fakeopen.com/v1/chat/completions")
                .method("POST", body)
                .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
                .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "*/*")
                .addHeader("Host", "ai.fakeopen.com")
                .addHeader("Connection", "keep-alive")
                .build();

**Comment by Changbaiqi** [comment]
> ```
>    Request request = new Request.Builder()
>             .url("https://ai.fakeopen.com/v1/chat/completions")
>             .method("POST", body)
>             .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
>             .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
>             .addHeader("Content-Type", "application/json")
>             .addHeader("Accept", "*/*")
>             .addHeader("Host", "ai.fakeopen.com")
>             .addHeader("Connection", "keep-alive")
>             .build();
> ```

这个是我写的一个用于便捷构建openai接口访问回复的工具类。这样机器人开发者就可以直接掉调用次工具类使用chatgpt了。

**Comment by jiangdengke** [comment]
> > ```
> >    Request request = new Request.Builder()
> >             .url("https://ai.fakeopen.com/v1/chat/completions")
> >             .method("POST", body)
> >             .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
> >             .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
> >             .addHeader("Content-Type", "application/json")
> >             .addHeader("Accept", "*/*")
> >             .addHeader("Host", "ai.fakeopen.com")
> >             .addHeader("Connection", "keep-alive")
> >             .build();
> > ```
> 
> 这个是我写的一个用于便捷构建openai接口访问回复的工具类。这样机器人开发者就可以直接掉调用次工具类使用chatgpt了。

因为我看到前面token啥的，所以猜测是抓包（我也不懂这些），顺着这个网址进去https://ai.fakeopen.com发现里面并没有api文档，请问大佬是怎样调用的呢

**Comment by Changbaiqi** [comment]
> > > ```
> > >    Request request = new Request.Builder()
> > >             .url("https://ai.fakeopen.com/v1/chat/completions")
> > >             .method("POST", body)
> > >             .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
> > >             .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
> > >             .addHeader("Content-Type", "application/json")
> > >             .addHeader("Accept", "*/*")
> > >             .addHeader("Host", "ai.fakeopen.com")
> > >             .addHeader("Connection", "keep-alive")
> > >             .build();
> > > ```
> > 
> > 
> > 这个是我写的一个用于便捷构建openai接口访问回复的工具类。这样机器人开发者就可以直接掉调用次工具类使用chatgpt了。
> 
> 因为我看到前面token啥的，所以猜测是抓包（我也不懂这些），顺着这个网址进去[https://ai.fakeopen.com发现里面并没有api文档，请问大佬是怎样调用的呢](https://ai.fakeopen.com%E5%8F%91%E7%8E%B0%E9%87%8C%E9%9D%A2%E5%B9%B6%E6%B2%A1%E6%9C%89api%E6%96%87%E6%A1%A3%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%A4%A7%E4%BD%AC%E6%98%AF%E6%80%8E%E6%A0%B7%E8%B0%83%E7%94%A8%E7%9A%84%E5%91%A2)

我是抓包自己分析的

**Comment by jiangdengke** [comment]
> 

大佬，抓包也是要api_key的吧，我刚才把那个openai文件夹复制过来，结合readme使用,报了this.authorizationList" is null的错误。
测试代码如下：
public class test {
    private final static ArrayList<GPTAnswer> list = new ArrayList<>();
    @Test
    public void test1(){
        GPTAnswer gptAnswer = new GPTAnswer();
        gptAnswer.setRole("user");
        gptAnswer.setContent("你好");
        list.add(gptAnswer);
        OpenAI openAI = new OpenAI.Builder()
                .messages(list)
                .toReply();
        System.out.println(openAI.getReplyMessage());

    }
}

**Comment by jiangdengke** [comment]
> > > > ```
> > > >    Request request = new Request.Builder()
> > > >             .url("https://ai.fakeopen.com/v1/chat/completions")
> > > >             .method("POST", body)
> > > >             .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
> > > >             .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
> > > >             .addHeader("Content-Type", "application/json")
> > > >             .addHeader("Accept", "*/*")
> > > >             .addHeader("Host", "ai.fakeopen.com")
> > > >             .addHeader("Connection", "keep-alive")
> > > >             .build();
> > > > ```
> > > 
> > > 
> > > 这个是我写的一个用于便捷构建openai接口访问回复的工具类。这样机器人开发者就可以直接掉调用次工具类使用chatgpt了。
> > 
> > 
> > 因为我看到前面token啥的，所以猜测是抓包（我也不懂这些），顺着这个网址进去[https://ai.fakeopen.com发现里面并没有api文档，请问大佬是怎样调用的呢](https://ai.fakeopen.com%E5%8F%91%E7%8E%B0%E9%87%8C%E9%9D%A2%E5%B9%B6%E6%B2%A1%E6%9C%89api%E6%96%87%E6%A1%A3%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%A4%A7%E4%BD%AC%E6%98%AF%E6%80%8E%E6%A0%B7%E8%B0%83%E7%94%A8%E7%9A%84%E5%91%A2)
> 
> 我是抓包自己分析的

大佬，抓包也是要api_key的吧，我刚才把那个openai文件夹复制过来，结合readme使用,报了this.authorizationList" is null的错误。
测试代码如下：
public class test {
private final static ArrayList list = new ArrayList<>();
@test
public void test1(){
GPTAnswer gptAnswer = new GPTAnswer();
gptAnswer.setRole("user");
gptAnswer.setContent("你好");
list.add(gptAnswer);
OpenAI openAI = new OpenAI.Builder()
.messages(list)
.toReply();
System.out.println(openAI.getReplyMessage());

}
}

**Comment by jiangdengke** [comment]
大佬，求回复

**Comment by Changbaiqi** [comment]
> > > > > ```
> > > > >    Request request = new Request.Builder()
> > > > >             .url("https://ai.fakeopen.com/v1/chat/completions")
> > > > >             .method("POST", body)
> > > > >             .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
> > > > >             .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
> > > > >             .addHeader("Content-Type", "application/json")
> > > > >             .addHeader("Accept", "*/*")
> > > > >             .addHeader("Host", "ai.fakeopen.com")
> > > > >             .addHeader("Connection", "keep-alive")
> > > > >             .build();
> > > > > ```
> > > > 
> > > > 
> > > > 这个是我写的一个用于便捷构建openai接口访问回复的工具类。这样机器人开发者就可以直接掉调用次工具类使用chatgpt了。
> > > 
> > > 
> > > 因为我看到前面token啥的，所以猜测是抓包（我也不懂这些），顺着这个网址进去[https://ai.fakeopen.com发现里面并没有api文档，请问大佬是怎样调用的呢](https://ai.fakeopen.com%E5%8F%91%E7%8E%B0%E9%87%8C%E9%9D%A2%E5%B9%B6%E6%B2%A1%E6%9C%89api%E6%96%87%E6%A1%A3%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%A4%A7%E4%BD%AC%E6%98%AF%E6%80%8E%E6%A0%B7%E8%B0%83%E7%94%A8%E7%9A%84%E5%91%A2)
> > 
> > 
> > 我是抓包自己分析的
> 
> 大佬，抓包也是要api_key的吧，我刚才把那个openai文件夹复制过来，结合readme使用,报了this.authorizationList" is null的错误。 测试代码如下： public class test { private final static ArrayList list = new ArrayList<>(); @test public void test1(){ GPTAnswer gptAnswer = new GPTAnswer(); gptAnswer.setRole("user"); gptAnswer.setContent("你好"); list.add(gptAnswer); OpenAI openAI = new OpenAI.Builder() .messages(list) .toReply(); System.out.println(openAI.getReplyMessage());
> 
> } }

对的，这个key就是自己账号的OpenAi的申请的key

**Comment by jiangdengke** [comment]
> 



> > > > > > ```
> > > > > >    Request request = new Request.Builder()
> > > > > >             .url("https://ai.fakeopen.com/v1/chat/completions")
> > > > > >             .method("POST", body)
> > > > > >             .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
> > > > > >             .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
> > > > > >             .addHeader("Content-Type", "application/json")
> > > > > >             .addHeader("Accept", "*/*")
> > > > > >             .addHeader("Host", "ai.fakeopen.com")
> > > > > >             .addHeader("Connection", "keep-alive")
> > > > > >             .build();
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 这个是我写的一个用于便捷构建openai接口访问回复的工具类。这样机器人开发者就可以直接掉调用次工具类使用chatgpt了。
> > > > 
> > > > 
> > > > 因为我看到前面token啥的，所以猜测是抓包（我也不懂这些），顺着这个网址进去[https://ai.fakeopen.com发现里面并没有api文档，请问大佬是怎样调用的呢](https://ai.fakeopen.com%E5%8F%91%E7%8E%B0%E9%87%8C%E9%9D%A2%E5%B9%B6%E6%B2%A1%E6%9C%89api%E6%96%87%E6%A1%A3%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%A4%A7%E4%BD%AC%E6%98%AF%E6%80%8E%E6%A0%B7%E8%B0%83%E7%94%A8%E7%9A%84%E5%91%A2)
> > > 
> > > 
> > > 我是抓包自己分析的
> > 
> > 
> > 大佬，抓包也是要api_key的吧，我刚才把那个openai文件夹复制过来，结合readme使用,报了this.authorizationList" is null的错误。 测试代码如下： public class test { private final static ArrayList list = new ArrayList<>(); @test public void test1(){ GPTAnswer gptAnswer = new GPTAnswer(); gptAnswer.setRole("user"); gptAnswer.setContent("你好"); list.add(gptAnswer); OpenAI openAI = new OpenAI.Builder() .messages(list) .toReply(); System.out.println(openAI.getReplyMessage());
> > } }
> 
> 对的，这个key就是自己账号的OpenAi的申请的key

大佬，但是我没在你的代码里找到可以填key的地方

**Comment by Changbaiqi** [comment]
> > 
> 
> > > > > > > ```
> > > > > > >    Request request = new Request.Builder()
> > > > > > >             .url("https://ai.fakeopen.com/v1/chat/completions")
> > > > > > >             .method("POST", body)
> > > > > > >             .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
> > > > > > >             .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
> > > > > > >             .addHeader("Content-Type", "application/json")
> > > > > > >             .addHeader("Accept", "*/*")
> > > > > > >             .addHeader("Host", "ai.fakeopen.com")
> > > > > > >             .addHeader("Connection", "keep-alive")
> > > > > > >             .build();
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 这个是我写的一个用于便捷构建openai接口访问回复的工具类。这样机器人开发者就可以直接掉调用次工具类使用chatgpt了。
> > > > > 
> > > > > 
> > > > > 因为我看到前面token啥的，所以猜测是抓包（我也不懂这些），顺着这个网址进去[https://ai.fakeopen.com发现里面并没有api文档，请问大佬是怎样调用的呢](https://ai.fakeopen.com%E5%8F%91%E7%8E%B0%E9%87%8C%E9%9D%A2%E5%B9%B6%E6%B2%A1%E6%9C%89api%E6%96%87%E6%A1%A3%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%A4%A7%E4%BD%AC%E6%98%AF%E6%80%8E%E6%A0%B7%E8%B0%83%E7%94%A8%E7%9A%84%E5%91%A2)
> > > > 
> > > > 
> > > > 我是抓包自己分析的
> > > 
> > > 
> > > 大佬，抓包也是要api_key的吧，我刚才把那个openai文件夹复制过来，结合readme使用,报了this.authorizationList" is null的错误。 测试代码如下： public class test { private final static ArrayList list = new ArrayList<>(); @test public void test1(){ GPTAnswer gptAnswer = new GPTAnswer(); gptAnswer.setRole("user"); gptAnswer.setContent("你好"); list.add(gptAnswer); OpenAI openAI = new OpenAI.Builder() .messages(list) .toReply(); System.out.println(openAI.getReplyMessage());
> > > } }
> > 
> > 
> > 对的，这个key就是自己账号的OpenAi的申请的key
> 
> 大佬，但是我没在你的代码里找到可以填key的地方

有的，我的代码设计是使用了链式建造者模式的范式。
所以我在使用的时候，只要这样写就行。
`OpenAI openAI = new OpenAI.Builder()
                .messages(gptAnswerMap.get(receiveMessage.getSendQQ()))
                .authorizationList(tokenList)
                .toReply();//将回复信息加入`

**Comment by jiangdengke** [comment]
> > > 
> > 
> > 
> > > > > > > > ```
> > > > > > > >    Request request = new Request.Builder()
> > > > > > > >             .url("https://ai.fakeopen.com/v1/chat/completions")
> > > > > > > >             .method("POST", body)
> > > > > > > >             .addHeader("Authorization", "Bearer "+authorizationList.get(authIndex))
> > > > > > > >             .addHeader("User-Agent", "Apifox/1.0.0 (https://www.apifox.cn)")
> > > > > > > >             .addHeader("Content-Type", "application/json")
> > > > > > > >             .addHeader("Accept", "*/*")
> > > > > > > >             .addHeader("Host", "ai.fakeopen.com")
> > > > > > > >             .addHeader("Connection", "keep-alive")
> > > > > > > >             .build();
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > 这个是我写的一个用于便捷构建openai接口访问回复的工具类。这样机器人开发者就可以直接掉调用次工具类使用chatgpt了。
> > > > > > 
> > > > > > 
> > > > > > 因为我看到前面token啥的，所以猜测是抓包（我也不懂这些），顺着这个网址进去[https://ai.fakeopen.com发现里面并没有api文档，请问大佬是怎样调用的呢](https://ai.fakeopen.com%E5%8F%91%E7%8E%B0%E9%87%8C%E9%9D%A2%E5%B9%B6%E6%B2%A1%E6%9C%89api%E6%96%87%E6%A1%A3%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%A4%A7%E4%BD%AC%E6%98%AF%E6%80%8E%E6%A0%B7%E8%B0%83%E7%94%A8%E7%9A%84%E5%91%A2)
> > > > > 
> > > > > 
> > > > > 我是抓包自己分析的
> > > > 
> > > > 
> > > > 大佬，抓包也是要api_key的吧，我刚才把那个openai文件夹复制过来，结合readme使用,报了this.authorizationList" is null的错误。 测试代码如下： public class test { private final static ArrayList list = new ArrayList<>(); @test public void test1(){ GPTAnswer gptAnswer = new GPTAnswer(); gptAnswer.setRole("user"); gptAnswer.setContent("你好"); list.add(gptAnswer); OpenAI openAI = new OpenAI.Builder() .messages(list) .toReply(); System.out.println(openAI.getReplyMessage());
> > > > } }
> > > 
> > > 
> > > 对的，这个key就是自己账号的OpenAi的申请的key
> > 
> > 
> > 大佬，但是我没在你的代码里找到可以填key的地方
> 
> 有的，我的代码设计是使用了链式建造者模式的范式。 所以我在使用的时候，只要这样写就行。 `OpenAI openAI = new OpenAI.Builder() .messages(gptAnswerMap.get(receiveMessage.getSendQQ())) .authorizationList(tokenList) .toReply();//将回复信息加入`

看起来是填在authorizationList(tokenList)里面，但是我点进去也没找到可以填key的地方，求大佬指点

**Comment by Changbaiqi** [comment]
> 

其中authorizationList填入的List<String>其实就是key。我设计成了可以填入多个key，这样就可以防止一个账号的key失效后就不能用了，我设计的时候是，如果一个key失效那么会自动尝试下一个key进行。你详细你可以看看OpenAI这个类里面的设计。

**Comment by jiangdengke** [comment]
> > 
> 
> 其中authorizationList填入的List其实就是key。我设计成了可以填入多个key，这样就可以防止一个账号的key失效后就不能用了，我设计的时候是，如果一个key失效那么会自动尝试下一个key进行。你详细你可以看看OpenAI这个类里面的设计。

okok
